name: Terraform Apply (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type APPLY to confirm apply"
        required: true

jobs:
  terraform-apply:
    name: Manual Terraform Apply
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm == 'APPLY' }}

    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    #   GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_JSON }}
    #   GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    #   GCP_REGION: ${{ secrets.GCP_REGION }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        working-directory: terraform
      
      - name: Save Terraform Outputs
        run: terraform output -json > tf_outputs.json
        working-directory: terraform
      
      - name: Upload Terraform Outputs
        uses: actions/upload-artifact@v5
        with:
          name: terraform-outputs
          path: terraform/tf_outputs.json
          retention-days: 3
